services:
  redis:
    image: redis:7-alpine
    container_name: lovediary_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - watcher_file

volumes:
  redis_data:

networks:
  watcher_file:
    driver: bridge